name: .NET

on: [push,pull_request]

jobs:
  build:
    name: Initialize build .NET
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Framework 4.8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: "4.8"
    - name: Restore dependencies
      run: nuget restore
    - name: Build
      run: msbuild /p:Configuration=Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
