name: .NET

on:
  push:
    branches: [ "1.0.0" ]
  pull_request:
    branches: [ "1.0.0" ]

jobs:
  build:
    name: Initialize build .NET
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
