name: .NET

on: [push,pull_request]

jobs:
  build:
    name: Initialize build .NET
    runs-on: windows-2019 # Используем окружение с .NET Framework 4.8

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: nuget restore
    - name: Build
      run: msbuild /p:Configuration=Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
